### ISSUE TITLE
Navigate/Replace with transition methods in stacked_services do not conform to the routes in the navigation stack

### ISSUE THREAD

**Issue by iamelio** [FilledStacks/stacked#685]
Using the `navigateWithTransition` or `replaceWithTransition` methods exposed by `navigationService` as of `stacked_services 0.9.1` always push a new route named `/Widget`, this seems to be the case with previous versions too, but I recently started using stacked with Flutter web, and this has been especially noticeable.

**Main Menu:**

![image](https://user-images.githubusercontent.com/87503695/177113866-87d2b43d-0847-4486-902c-9d1fa456f402.png)

**Leaderboard:**
Navigating to the leaderboard view works as expected, but the route name pushed onto in the navigation stack is `/Widget`

![image](https://user-images.githubusercontent.com/87503695/177120122-40a96940-e15d-4711-baec-0f23a109b832.png)

You can easily reproduce this by creating a dummy app with stacked_cli so all stacked features are integrated (the issue occurs with or without the cli), and two screens, and use either navigate/replace with transition methods to navigate between them on Flutter web.

**Solutions tried to fix:**

- I have tried using the `StackedService.routeObserver` as a navigation observer, but this had no effect.

- Using the `navigateTo` or the newer `navigateTo{RouteName}` method achieves the desired effect, but I would also like a custom transition duration, which I can't define with any of these methods.

- A **working solution** I discovered when going through the source code is that exposing the `routeName` property to any of these methods and defining it lets me achieve the desired effect.

So calling the `navigateToTransition` method like this:
```
 _navigationService.navigateWithTransition(
      const LeaderboardView(),
      duration: const Duration(milliseconds: 1200),
      transitionStyle: Transition.fade,
      routeName: Routes.leaderboardView,
    );
```

works with the desired effect:

![image](https://user-images.githubusercontent.com/87503695/177127692-46087cc0-aa0b-4e50-8feb-6aa9c0169fad.png)

I have made a PR with this working solution.

I am also currently on `Flutter 3.0.2`

**Comment by Eimen2018** [comment]
stacked_services: 0.9.2
