### ISSUE TITLE
Unhandled exception when creating application using web template

### ISSUE THREAD

**Issue by vladchuk** [FilledStacks/stacked#882]
The following exception is thrown twice while executing create app [app] --template=web
Command executed in Android Studio terminal on Windows 11 OS. Project creation seems to succeed.

<pre>
Cleaning project...
Unhandled exception:
RangeError (index): Invalid value: Only valid value is 0: 2
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      CreateAppCommand._clean (package:stacked_cli/src/commands/create/create_app_command.dart:102:33)
<asynchronous suspension>
#2      CreateAppCommand.run (package:stacked_cli/src/commands/create/create_app_command.dart:80:5)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
</pre>

**Comment by ferrarafer** [comment]
Can you run `stacked --version` an reply with the output here please? Did you try it outside Android Studio?

**Comment by FilledStacks** [comment]
@vladchuk is this still happening? It's working on my side.

**Comment by vladchuk** [comment]
Stacked version is 1.4.0. Exactly same error happens when run in the command prompt.
My concern is that despite the project being generated, it might be somehow "deficient".

**Comment by vladchuk** [comment]
Some insight into this issue. When cleaning project, dart analyze is parsed using bullet as separator:
`final log = i.split(' • ')[2].split(':');`

However, in my case analyzer outputs dashes (-), not bullets. Changing the above line to use dashes fixed the issue for me.
FWIW, the command line outputs bullets, which I don't quite understand (when dumped to a file it's dashes).

I hope this helps you to troubleshoot further.

**Comment by vladchuk** [comment]
Also, when this (any?) error happens, the command seems to be executed twice. Bug or feature?

**Comment by FilledStacks** [comment]
@vladchuk both sounds like bugs to me. I'll see if there's a way for us to know what to split by. Thanks for the details!

**Comment by FilledStacks** [comment]
We won't be adding the functionality for custom separators. We have only received this one report. We'll be tackling the issues on the Project board as higher priority.
