### ISSUE TITLE
How to include dependencies like this?

### ISSUE THREAD

**Issue by ziqq** [FilledStacks/stacked#953]
### I don't understand how to do in such cases. Can you suggest?

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/20646071/233274587-b9a2acec-9eb7-4d23-93c9-f6b8f3469a0e.png">

Like

```dart
abstract class ThirdPartyServicesModule {
  @lazySingleton
  FirebaseMessaging get firebaseMessaging => FirebaseMessaging.instance;
}
```

**Comment by FilledStacks** [comment]
Use a [presolve registration](https://github.com/Stacked-Org/stacked/blob/master/README_old.md#dependency-registration).

**Comment by ziqq** [comment]
> Use a [presolve registration](https://github.com/Stacked-Org/stacked/blob/master/README_old.md#dependency-registration).

#### It's not valid. Because:

```dart
/// Returns an instance using the default [FirebaseApp].
static FirebaseMessaging get instance {
  FirebaseApp defaultAppInstance = Firebase.app();
  return FirebaseMessaging._instanceFor(app: defaultAppInstance);
}
```

<img width="550" alt="image" src="https://github.com/Stacked-Org/stacked/assets/20646071/d55fec26-691d-4b44-bac4-ffc4ea18731a">

**Comment by ziqq** [comment]
#### Ok i try to include like this. I hope this will work.

```dart
LazySingleton(classType: FirebaseMessaging)
```

**Comment by FilledStacks** [comment]
You should probably learn stacked basics first from the older videos on my channel.

**Comment by ziqq** [comment]
I was find the solution.
